### ISSUE TITLE
Libre-office: Can open dmenu and search menu items, but not execute action

### ISSUE THREAD

**Issue by Jazoray** [jamcnaughton/hud-menu#2]
**Environment:**
Linux Mint XFCE x86
Python 3.4.3
LibreOffice 5.0.3.2 00m0(Build:2)

**steps to reproduce:**
1. while libreoffice (for example libreoffice-writer) is focused, invoke the hud menu
2. select an action from the list
3. press enter

**expected behavior:**
the selected action is run

**actual behavior:**
libreoffice does not execute the selected menu item action

**errors encountered:**

jard@jard-VirtualBox ~ $ sleep 3 && python3 ~/applications/i3-hud-menu.py
(user switching focus to libreoffice writer and selecting action)
ERROR:dbus.connection:Unable to set arguments ('win..uno:Cut', [], {}) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
Traceback (most recent call last):
  File "/home/jard/applications/i3-hud-menu.py", line 181, in <module>
    try_gtk_interface(gtk_bus_name_cmd, gtk_object_path_cmd)
  File "/home/jard/applications/i3-hud-menu.py", line 158, in try_gtk_interface
    gtk_action_object_actions_iface.Activate(action.replace('unity.', ''), [], dict())
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in **call**
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty list

**further information**

I consider this issue especially severe, because libreoffice detects that an external menu us being used and hides the normal menubar. I know of no way to restore the menubar in libreoffice

**Comment by Jazoray** [comment]
**temporary workaround:**

remove the package libreoffice-gtk. this will remove the global menubar integration and bring back the normal menu. of course, then the i3-hud-menu can't be used at all with  libreoffice. but at least we get any useable menubar.

**Comment by jmaris** [comment]
can also confirm this issue

**Comment by jamcnaughton** [comment]
Its appears LibreOffice does not register its menu entries with org.gtk.Actions in the dbus. Same also applies to the gtk3 version of gedit.
